### ISSUE TITLE
v0.9.6: Failing to import modules

### ISSUE THREAD

**Issue by Boruch-Baum** [firecat53/urlscan#108]
I've `git clone`d the repository, and performed a `pip install --user -e ./`, but when attempting to use urlscan ...

```
Traceback (most recent call last):
  File "/home/optimum/.local/bin/urlscan", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/optimum/Projects/urlscan/bin/urlscan", line 28, in <module>
    from email import policy
ImportError: cannot import name policy
```

I'm using python 3.7 in debian.

From a python3 shell, I succeed in performing `from email import policy`

For giggles, I commented out the line, and received further similar errors for `BytesParser` and `DEVNULL`

Version 0.94 of `urlscan` had been working fine...

**Comment by Boruch-Baum** [comment]
I'm seeing that the `pip install` is creating file `urlscan.egg-link` in a python 2.7 directory ?! Is that expected/desirable? I notice it because it created the two levels of directory tree  `~/.local/lib/python2.7/site-packages`.

**Comment by Boruch-Baum** [comment]
OKAY! I still have python2 installed, so running `pip` was running the python2 version. Re-installing with `pip3` fixed the issue.
