### ISSUE TITLE
Crash on using urlscan with neomutt

### ISSUE THREAD

**Issue by Lippiece** [firecat53/urlscan#144]
The same as #69. Installed from Arch extra.

<details><summary>Traceback</summary>
<p>

```
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/urwid/event_loop/main_loop.py", line 435, in _run
    self.start()
  File "/usr/lib/python3.11/site-packages/urwid/event_loop/main_loop.py", line 400, in start
    raise CantUseExternalLoop(f"Screen {self.screen!r} doesn't support external event loops")
urwid.event_loop.main_loop.CantUseExternalLoop: Screen <urwid.display.curses.Screen object at 0x7f1f5f294550> doesn't support external event loops

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/urlscan", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/urlscan/__main__.py", line 192, in main
    tui.main()
  File "/usr/lib/python3.11/site-packages/urlscan/urlchoose.py", line 263, in main
    self.loop.run()
  File "/usr/lib/python3.11/site-packages/urwid/event_loop/main_loop.py", line 342, in run
    self._run()
  File "/usr/lib/python3.11/site-packages/urwid/event_loop/main_loop.py", line 438, in _run
    self._run_screen_event_loop()
  File "/usr/lib/python3.11/site-packages/urwid/event_loop/main_loop.py", line 500, in _run_screen_event_loop
    keys, raw = self.screen.get_input(True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/display/curses.py", line 349, in get_input
    keys, raw = self._get_input(self.max_tenths)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/display/curses.py", line 382, in _get_input
    key = self._getch(wait_tenths)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/display/curses.py", line 253, in _getch
    return self.s.getch()
           ^^^^^^^^^^^^^^
```

</p>
</details>

**Comment by firecat53** [comment]
I'm not able to replicate on Archlinux (installed and ran urlscan from the extra repo inside an Arch container). Is your system fully up to date and are you running urlscan version 1.0.1 and python 3.11? Did the crash happen when you hit enter on a link?
